name: Tauri v2 Release Process
on:
  workflow_dispatch:
    # You can optionally add inputs here if you want to parameterize the manual run
    # inputs:
    #   version:
    #     description: 'Release version'
    #     required: true
    #     default: '0.1.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_APPLICATION: "raki/raki"

jobs:
  draft:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release draft ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  build:
    needs: draft

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: install Linux dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1

      - name: build python backend for Linux and Windows
        if: matrix.os != 'macos-latest'
        run: |
          cd projects/llm_backend/
          uv venv
          . .venv/bin/activate
          uv sync
          cd app
          pyinstaller -F main.py --clean --hidden-import=pydantic --hidden-import=pydantic-core --hidden-import=pydantic.deprecated.decorator

      - name: build Tauri app for Linux
        if: matrix.os == "ubuntu-22.04"
        run: |
          mv dist/main dist/main-x86_64-unknown-linux-gnu
          cd ../../frontend
          yarn install --frozen-lockfile
          yarn tauri build

      - name: build Tauri app for Windows
        if: matrix.os == "windows-latest"
        run: |
          mv dist/main.exe dist/main-x86_64-pc-windows-msvc.exe
          cd ../../frontend
          yarn install --frozen-lockfile
          yarn tauri build
      # env:
      #   TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      #   TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      - name: build backend and Tauri binaries for mac
        if: matrix.os == 'macos-latest'
        run: |
          cd projects/llm_backend/
          uv venv
          . .venv/bin/activate
          uv sync
          cd app
          pyinstaller -F main.py --clean --hidden-import=pydantic --hidden-import=pydantic-core --hidden-import=pydantic.deprecated.decorator
          mv dist/main dist/main-aarch64-apple-darwin
          cd ../../frontend
          rustup target add x86_64-apple-darwin
          yarn install --frozen-lockfile
          yarn tauri build --target x86_64-apple-darwin
          yarn tauri build --target aarch64-apple-darwin
        # env:
        #   TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        #   TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  publish:
    needs: build

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: publish release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release publish ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}
