name: Tauri v2 Release Process
on:
  workflow_dispatch:
    # You can optionally add inputs here if you want to parameterize the manual run
    # inputs:
    #   version:
    #     description: 'Release version'
    #     required: true
    #     default: '0.1.0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_APPLICATION: "raki/raki"

jobs:
  draft:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release draft ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  build:
    needs: draft

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: build python backend and Tauri app for Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1
          cd projects/llm_backend/
          uv venv
          . .venv/bin/activate
          uv sync
          cd app
          pyinstaller -F main.py --clean --hidden-import=pydantic --hidden-import=pydantic-core --hidden-import=pydantic.deprecated.decorator
          mv dist/main dist/main-x86_64-unknown-linux-gnu
          cd ../../frontend
          yarn install --frozen-lockfile
          yarn tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: build python backend and Tauri app for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd projects/llm_backend/
          uv venv
          .\.venv\Scripts\activate
          uv sync
          cd app
          pyinstaller -F main.py --clean --hidden-import=pydantic --hidden-import=pydantic-core --hidden-import=pydantic.deprecated.decorator
          mv dist/main.exe dist/main-x86_64-pc-windows-msvc.exe
          cd ../../frontend
          yarn install --frozen-lockfile
          yarn tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: build backend and Tauri binaries for mac
        if: matrix.os == 'macos-latest'
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_PATH: ${{ secrets.APPLE_API_KEY_PATH }}
          APPLE_NOTARIZATION_API_PRIVATE_KEY: ${{ secrets.APPLE_NOTARIZATION_API_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        run: |
          # Create a directory for the API key and decode it there
          mkdir -p ~/private_keys
          echo $APPLE_NOTARIZATION_API_PRIVATE_KEY | base64 --decode > ~/private_keys/AuthKey.p8
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          security default-keychain -s build.keychain

          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Store certificate ID
          security find-identity -v -p codesigning build.keychain

          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | head -1)
          if [ -z "$CERT_INFO" ]; then
            echo "No signing certificates found in keychain!"
            exit 1
          fi
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV

          # Build process
          cd projects/llm_backend/
          uv venv
          . .venv/bin/activate
          uv sync
          cd app
          pyinstaller -F main.py --clean --hidden-import=pydantic --hidden-import=pydantic-core --hidden-import=pydantic.deprecated.decorator
          cp dist/main dist/main-aarch64-apple-darwin
          cp dist/main dist/main-x86_64-apple-darwin

          # Sign the Python executables
          codesign --force -s "$CERT_ID" --options runtime --timestamp dist/main-aarch64-apple-darwin
          codesign --force -s "$CERT_ID" --options runtime --timestamp dist/main-x86_64-apple-darwin

          # Create zip archives for notarization
          ditto -c -k --keepParent dist/main-aarch64-apple-darwin dist/main-aarch64-apple-darwin.zip
          ditto -c -k --keepParent dist/main-x86_64-apple-darwin dist/main-x86_64-apple-darwin.zip

          # Notarize the executables using API key
          xcrun notarytool submit dist/main-aarch64-apple-darwin.zip --key ~/private_keys/AuthKey.p8 --key-id "$APPLE_API_KEY" --issuer "$APPLE_API_ISSUER" --wait
          xcrun notarytool submit dist/main-x86_64-apple-darwin.zip --key ~/private_keys/AuthKey.p8 --key-id "$APPLE_API_KEY" --issuer "$APPLE_API_ISSUER" --wait

          cd ../../frontend
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          yarn install --frozen-lockfile
          yarn tauri build --target x86_64-apple-darwin --verbose
          yarn tauri build --target aarch64-apple-darwin --verbose

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  publish:
    needs: build

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: publish release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release publish ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}
